Correct kubeclient init and parameters in snapshot-metadata-lister
kubernetes-csi/external-snapshot-metadata pull request #90
Opened 2024-12-17 12:58 UTC by PrasadG193

**What type of PR is this?**

> /kind bug

**What this PR does / why we need it**:

This PR fixes few issues found while testing the client inside a pod:

- Adds support to initialize kubernetes client from inside pod
- Corrects parameter order in  createSecurityToken()

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2024-12-17 13:30 UTC, Rakshith-R approved these changes
LGTM thanks

2024-12-17 18:11 UTC, PrasadG193 commented
/assign @carlbraganza

2024-12-18 17:27 UTC, carlbraganza requested changes
Needs an update to the UT too.

2024-12-19 20:51 UTC, carlbraganza approved these changes
/lgtm

2024-12-19 21:30 UTC, merged